name: First workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: say_hello
        run: echo "Hello"
      - name: say_goodbye
        run: echo "Bye"
        
